# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Docker Build

inputs:
  docker-arch:
    required: true
  image-arch:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
    - name: Log into registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: suffix=_${{ inputs.image-arch }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: "./tools/container/Dockerfile"
        push: ${{ github.ref_type == 'tag' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.docker-arch }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
