# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-amd64:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/template/fwe-build"
        with:
          build-arch: "native"
          upload-arch: "amd64"
          docker-arch: "linux/amd64"

  build-arm64:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/template/fwe-build"
        with:
          build-arch: "cross-arm64"
          upload-arch: "arm64"
          docker-arch: "linux/arm64"

  build-armhf:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/template/fwe-build"
        with:
          build-arch: "cross-armhf"
          upload-arch: "armhf"

  docker-manifest:
    runs-on: ubuntu-18.04
    if: github.ref_type == 'tag'
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Create manifest
        run: |
          RELEASE_VERSION="${GITHUB_REF/refs\/tags\//}"
          docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${RELEASE_VERSION} \
            --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${RELEASE_VERSION}_amd64 \
            --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${RELEASE_VERSION}_arm64
          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${RELEASE_VERSION}
