# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-amd64:
    runs-on: ubuntu-18.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: "./.github/template/fwe-build"
      with:
        build-arch: "native"
        upload-arch: "amd64"

  build-arm64:
    runs-on: ubuntu-18.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: "./.github/template/fwe-build"
      with:
        build-arch: "cross-arm64"
        upload-arch: "arm64"

  build-armhf:
    runs-on: ubuntu-18.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: "./.github/template/fwe-build"
      with:
        build-arch: "cross-armhf"
        upload-arch: "armhf"
