# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Release Build

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build-amd64:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: cache-deps
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: deps-native
        key: ${{ runner.os }}-deps
  
    - name: install-deps
      run: |
        sudo ./tools/install-deps-native.sh
        sudo chown -R $(id -u):$(id -g) deps-native

    - name: build
      run: ./tools/build-fwe-native.sh

    - name: package
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir dist && cd dist
        cp ../build/src/executionmanagement/aws-iot-fleetwise-edge ../LICENSE ../THIRD-PARTY-LICENSES .
        RELEASE_VERSION="${GITHUB_REF/refs\/tags\//}"
        ASSET_FILENAME="aws-iot-fleetwise-edge-amd64.tar.gz"
        tar -zcf ../${ASSET_FILENAME} .
        UPLOAD_URL="https://uploads.github.com/repos/${{ github.repository }}/releases/${RELEASE_VERSION}/assets{?name,label}"
        gh release upload ${UPLOAD_URL} ${ASSET_FILENAME}
