# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Update AMI IDs Monthly

on:
  schedule:
    # Run on the first day of every month at 2 AM UTC
    - cron: "0 2 1 * *"
  workflow_dispatch:

jobs:
  update-cfn-ami-ids:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.UPDATE_CFN_AMI_IDS_ROLE }}
          aws-region: us-east-1
      - name: update-files
        run: |
          set -xeuo pipefail
          python3 tools/update-cfn-ami-ids.py --file tools/cfn-templates/fwdemo.yml                     --mapping AMIRegionMap      --arch arm64
          python3 tools/update-cfn-ami-ids.py --file tools/cfn-templates/fwddev.yml                     --mapping AMIRegionMapArm64 --arch arm64
          python3 tools/update-cfn-ami-ids.py --file tools/cfn-templates/fwddev.yml                     --mapping AMIRegionMapAmd64 --arch x86_64
          python3 tools/update-cfn-ami-ids.py --file tools/cfn-templates/vision-system-data-jupyter.yml --mapping AMIRegionMap      --arch arm64
          if git diff --quiet; then
            echo "No AMI updates needed"
          else
            echo "AMI updates detected"
            git config --global user.name "GitHub Actions"
            git config --global user.email "iotfleetwise@amazonaws.com"
            git checkout -b update-cfn-ami-ids-$(date +'%Y-%m-%d')
            git add .
            MESSAGE="Update AMIs $(date +'%Y-%m-%d')"
            git commit -m "${MESSAGE}"
            gh pr create -B main -H branch_to_merge --title "${MESSAGE}" --body-file .github/PULL_REQUEST_TEMPLATE.md
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
